### PR TITLE
Return codes fix and increased error reporting

### PR DESCRIPTION
**Pull request by jabjoe**

### CODE REVIEW

**Review by msperl — COMMENTED** [review]
has been fixed in V8 already (or was it V7?)

**Review by msperl — COMMENTED** [review]
has been added to V8

**Review by msperl — COMMENTED** [review]
Which one was really the bug?
Where was the return used?

**Comment by jabjoe** [comment]
The first commit (4d90b9f), the get mode one, was a bug. It also didn't fit in either anyway and was easy to cause that kind of bug because of it. The mode was used as a return code in mcp25xxfd_can_probe. The same commit also adds some warnings at site of failures to aid debug. Should have been a separate commit. Feel free to just take the fix in your own commit. Or I can split it.

Second commit (a139119) is also a bug, one we already discussed via email.

Third commit (f86727d) is just a warning that was useful ruling out SPI issues. Feel free to drop it.
Fourth commit (957ad4f) is also just a warning to aid debug. Feel free to drop it.

Firth commit (1588033) fixes a kernel crash when bringing down the CAN interface.

**Comment by msperl** [comment]
look at: https://github.com/msperl/linux-upstream/tree/upstream-5.2-master-80f23-mcp25xxfd-v8.0 for the latest (untested) version (see also email)

Let us discuss it from V8 and not V6 which is quite old now.

**Comment by jabjoe** [comment]
I will look at the new branch tomorrow and port any of the fixes required.

**Comment by msperl** [comment]
As far as I know all of this has been applied

**Pull request closed without merging**
